RubyMovies/config/routes.rb
RubyMovies::Application.routes.draw do

  get "/blocklists", to: "blocklists#index", as: "blocklist"
  delete "/blocklists/:blocked_user", to: "blocklists#destroy", as: "delete_blocklist"
  
  get "quizzes/new"
  get "quizzes/create"
  get "/questions/solve", to: "questions#solve"
  get "questions/quiz", to: "questions#quiz", as: "quiz_start"
  get "questions/quiz/new", to: "questions#new_quiz", as: "quiz_new"
  resources :questions do
    member do 
      post "active"
    end
  end

  get "messages/new/:mid", to: "messages#new", as: "message_respond"
  get "messages/outbox", to: "messages#outbox", as: "outbox_messages"
  get "messages/inbox", to: "messages#index", as: "inbox_messages"
  put "messages/block/:user", to: "messages#block", as: "block_user"
  delete "messages/:id", to: "messages#delete", as: "delete_message"
  resources :messages
  
  get 'search', to: 'films#tagsearch', as: "tag_search"
  get 'searchresult', to: 'films#searchresult', as: "search_result_films"
  get 'tags/:tag', to: 'films#index', as: :tag
  
  delete "comments/destroy/:id", to: "comments#destroy", as: "comments_destroy"

  get "films/top", to: "films#top", as: "films_top"
  post "films/:id/review/:rid", to: "films#review", as: "film_review"
  get "/films/suggested", to: "films#suggested", as: "suggested_films"
  resources :films do
    member do
      post "active"
      delete "rempicture"
    end
  end
  resources :films
  get "users/list", as: "manage_users"
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do 
    member do
      get "promote"
      post "promote"
    end
  end

  resources :films do
    resources :comments
  end

  root to: "films#index"

  

end

RubyMovies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RubyMovies</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
    <div id = "mainwrapper"> 
    	<h1>RubyMovies</h1>
        <div id = "links">
            <div><%= link_to_unless_current "Alle Filme", root_path %></div>
            <div><%= link_to_unless_current "Top-Filme", films_top_path %></div>
            <div><%= link_to_unless_current "Suche nach Tags", tag_search_url %></div>
            <div><%= link_to_signed_in "Film vorschlagen", new_film_path %></div>
            <div><%= link_to_admin_mod "Vorgeschlagene Filme", suggested_films_url %></div>

            <br />

            <div><%= link_to_unless(filmquizlinkdisabled?, "Filmquiz", quiz_start_path) if user_signed_in? %></div>
            <div><%= link_to_signed_in "Frage vorschlagen", new_question_url %></div>
            <div><%= link_to_admin_mod "Fragen verwalten", questions_url %></div>

            <br />

            <div><%= link_to_unless(messagelinkdisabled?, "Nachrichten(#{new_message_count})", inbox_messages_path) if user_signed_in? %></div>
            <div><%= link_to_unless_current('Administration', manage_users_url) if admin_signed_in? %></div>
            <div><%= link_to_unless_current('Logout', destroy_user_session_path, :method => :delete) if user_signed_in? %></div>
            <div><%= link_to_unless_current('Registrierung', new_user_registration_url) unless user_signed_in? %></div>
            <div><%= link_to('Login', new_user_session_url) unless user_signed_in? %></div>  
        </div>
        <div id = "content">
            <p id="notice"><%= notice %></p>
            <p id="alert"><%= alert %></p>
            <%= yield %>
        </div>
    </div>
</body>
</html>