RubyMovies/config/routes.rb
RubyMovies::Application.routes.draw do

  get "/blocklists", to: "blocklists#index", as: "blocklist"
  delete "/blocklists/:blocked_user", to: "blocklists#destroy", as: "delete_blocklist"
  
  get "quizzes/new"
  get "quizzes/create"
  get "/questions/solve", to: "questions#solve"
  get "questions/quiz", to: "questions#quiz", as: "quiz_start"
  get "questions/quiz/new", to: "questions#new_quiz", as: "quiz_new"
  resources :questions do
    member do 
      post "active"
    end
  end

  get "messages/new/:mid", to: "messages#new", as: "message_respond"
  get "messages/outbox", to: "messages#outbox", as: "outbox_messages"
  get "messages/inbox", to: "messages#index", as: "inbox_messages"
  put "messages/block/:user", to: "messages#block", as: "block_user"
  delete "messages/:id", to: "messages#delete", as: "delete_message"
  resources :messages
  
  get 'search', to: 'films#tagsearch', as: "tag_search"
  get 'searchresult', to: 'films#searchresult', as: "search_result_films"
  get 'tags/:tag', to: 'films#index', as: :tag
  
  delete "comments/destroy/:id", to: "comments#destroy", as: "comments_destroy"

  get "films/top", to: "films#top", as: "films_top"
  post "films/:id/review/:rid", to: "films#review", as: "film_review"
  get "/films/suggested", to: "films#suggested", as: "suggested_films"
  resources :films do
    member do
      post "active"
      delete "rempicture"
    end
  end
  resources :films
  get "users/list", as: "manage_users"
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do 
    member do
      get "promote"
      post "promote"
    end
  end

  resources :films do
    resources :comments
  end

  root to: "films#index"

  

end

RubyMovies/app/models/message.rb
class Message < ActiveRecord::Base
	# Informationen zur Handhabung mehrmaliger Assoziation mit der selben Tabelle aus:
	# http://www.spacevatican.org/2008/5/6/creating-multiple-associations-with-the-same-table/
	belongs_to :sender, :class_name => 'User'
	belongs_to :recipient, :class_name => 'User'

	def delete user 
		if self.sender == user
			if self.deleted_by_recipient
				destroy
			else
				self.deleted_by_sender = true
				self.save
			end
			true
		end

		if self.recipient == user
			if self.deleted_by_sender
				destroy
			else
				self.deleted_by_recipient = true
				self.save
			end
			false
		end
	end

	def set_read
		self.read = true
		self.save
	end
end

RubyMovies/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  authorize_resource

  before_action :set_message, only: [:show, :edit, :update, :destroy, :delete]

  # GET /messages
  # GET /messages.json
  # GET /messages/inbox
  def index
    @unread_messages = Message.where(recipient: current_user, read: false, deleted_by_recipient: false).order(created_at: :desc).page params[:page]
    @read_messages = Message.where(recipient: current_user, read: true, deleted_by_recipient: false).order(created_at: :desc).page params[:page]
  end

  # GET /messages/outbox
  def outbox
    @messages = Message.where(sender: current_user, deleted_by_sender: false).order(created_at: :desc).page params[:page]
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    #message = Message.find(params[:id])
    message = Message.where("id = ? AND (sender_id = ? OR recipient_id = ?)",params[:id], current_user.id, current_user.id ).take
    if (message.recipient == current_user) && !message.read
      message.set_read
    end
  end

  # GET /messages/new
  def new
    @message = Message.new
    if params[:mid] != nil
      m = Message.find(params[:mid])
      @message.recipient = m.sender
      @message.subject = "AW: #{m.subject}"
      @message.text = "\n----------\n#{m.text}"
    end
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.sender = current_user
    if current_user.is_allowed_to_send? params[:message][:recipient_id]
      respond_to do |format|
        if @message.save
          format.html { redirect_to @message, notice: 'Nachricht erfolreich verschickt.' }
          format.json { render action: 'show', status: :created, location: @message }
        else
          format.html { render action: 'new' }
          format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_message_path, notice: 'Sie dürfen an diesen Benutzer keine Nachricht verschicken!'
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def delete
    if @message.delete current_user
      redirect_to outbox_messages_path
    else
      redirect_to inbox_messages_path
    end
  end

  def block
    if current_user.add_to_blocklist params[:user] 
      notice = "Benutzer ist nun blockiert!"
    else
      notice = "Der Benutzer ist bereits blockiert!"
    end
    redirect_to inbox_messages_path, notice: notice
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_id, :recipient_id, :subject, :text, :read, :deleted_by_sender, :deleted_by_recipient)
    end
  end

RubyMovies/app/helpers/messages_helper.rb
module MessagesHelper
	def new_message_count
		Message.where(recipient: current_user, read: false, deleted_by_recipient: false).count
	end
end

RubyMovies/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>An:
      <%= f.collection_select(:recipient_id, User.where.not(name: current_user.name).order('name DESC'), :id, :name ) %>
    </p>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RubyMovies/app/views/messages/_link.html.erb
<%= link_to_unless_current 'Posteingang', inbox_messages_path %>
<%= link_to_unless_current 'Postausgang', outbox_messages_path %>
<%= link_to_unless_current 'Neue Nachricht', new_message_path %>
<%= link_to_unless_current 'Blockierte Benutzer', blocklist_path %>

RubyMovies/app/views/messages/_messages.html.erb
<% unless messages.empty? %>
  
  <table>
    <thead>
      <tr>
        <% if sender %>
          <th>Von</th>
        <% else %>
          <th>An</th>
        <% end %>
        <th>Datum</th>
        <th>Betreff</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% messages.each do |message| %>
        <tr>
          <% if sender %>
            <td><%= message.sender.name %></td>
          <% else %>
            <td><%= message.recipient.name %></td>
          <% end %>
          <td><%= message.created_at.to_formatted_s(:db) %></td>
          <td><%= message.subject %></td>
          <td><%= link_to 'lesen', message %></td>
          <td><%= link_to 'löschen', delete_message_path(message.id), method: :delete %></td>
          <td><%= link_to 'blockieren', block_user_path(message.sender), method: :put, data: { confirm: 'Sind Sie sicher?'}  if sender %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <%= error %>

<% end %>

RubyMovies/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

RubyMovies/app/views/messages/index.html.erb
<%= render 'link' %>
<h1>Posteingang</h1>

<h2>Ungelesene Nachrichten</h2>

<%= render :partial => "messages", :locals => { :messages => @unread_messages, :error => "Keine ungelesenen Nachrichten vorhanden.", :sender => true } %>
<%= paginate @unread_messages %>

<h2>Gelesene Nachrichten</h2>

<%= render :partial => "messages", :locals => { :messages => @read_messages, :error => "Keine schon gelesenen Nachrichten vorhanden.", :sender => true } %>
<%= paginate @read_messages %>

RubyMovies/app/views/messages/new.html.erb
<%= render 'link' %>
<h1>New message</h1>

<%= render 'form' %>

<%= back %>

RubyMovies/app/views/messages/outbox.html.erb
<%= render 'link' %>
<h1>Postausgang</h1>

<h2>Gesendete Nachrichten</h2>

<%= render :partial => "messages", :locals => { :messages => @messages, :error => "Keine gesendeten Nachrichten vorhanden.", :sender => false } %>

<%= paginate @messages %>

RubyMovies/app/views/messages/show.html.erb
<%= render 'link' %>
<p>
  <strong>Von:</strong>
  <%= @message.sender.name %>
</p>

<p>
  <strong>Betreff:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Text:</strong>
  <%= simple_format @message.text %>
</p>

<% if current_user == @message.recipient %>
  <%= link_to 'Antworten', message_respond_path(@message.id) %>
<% end %>
<%= back %>