RubyMovies/config/routes.rb
RubyMovies::Application.routes.draw do

  get "/blocklists", to: "blocklists#index", as: "blocklist"
  delete "/blocklists/:blocked_user", to: "blocklists#destroy", as: "delete_blocklist"
  
  get "quizzes/new"
  get "quizzes/create"
  get "/questions/solve", to: "questions#solve"
  get "questions/quiz", to: "questions#quiz", as: "quiz_start"
  get "questions/quiz/new", to: "questions#new_quiz", as: "quiz_new"
  resources :questions do
    member do 
      post "active"
    end
  end

  get "messages/new/:mid", to: "messages#new", as: "message_respond"
  get "messages/outbox", to: "messages#outbox", as: "outbox_messages"
  get "messages/inbox", to: "messages#index", as: "inbox_messages"
  put "messages/block/:user", to: "messages#block", as: "block_user"
  delete "messages/:id", to: "messages#delete", as: "delete_message"
  resources :messages
  
  get 'search', to: 'films#tagsearch', as: "tag_search"
  get 'searchresult', to: 'films#searchresult', as: "search_result_films"
  get 'tags/:tag', to: 'films#index', as: :tag
  
  delete "comments/destroy/:id", to: "comments#destroy", as: "comments_destroy"

  get "films/top", to: "films#top", as: "films_top"
  post "films/:id/review/:rid", to: "films#review", as: "film_review"
  get "/films/suggested", to: "films#suggested", as: "suggested_films"
  resources :films do
    member do
      post "active"
      delete "rempicture"
    end
  end
  resources :films
  get "users/list", as: "manage_users"
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do 
    member do
      get "promote"
      post "promote"
    end
  end

  resources :films do
    resources :comments
  end

  root to: "films#index"

  

end

RubyMovies/app/models/film.rb
class Film < ActiveRecord::Base
	#relations
	has_many :film_participants
	has_many :participants, through: :film_participants
	has_many :reviews
	has_many :users, through: :reviews
	has_many :comments

	#make picture upload work
	mount_uploader :picture, PictureUploader

	#http://stackoverflow.com/questions/5331014/check-if-given-string-is-an-url
	validates :link, :format => URI::regexp(%w(http https)), :allow_blank => true

	#http://stackoverflow.com/questions/8481132/rails-3-make-text-field-accept-only-numeric-values
	validates :year, :numericality => {:only_integer => true}, :allow_blank => true

	validates :title, :presence => true

	#make films taggable
	acts_as_taggable

	def self.findbytags(tags)
		where(active: true).tagged_with(tags, :any => true)
	end

	def review note, user
		r = Review.new
		r.note = note
    	r.film = self
    	r.user = user
    	r.save
	end

	def set_active
		self.active = true
    	self.save
	end
end

RubyMovies/app/controllers/films_controller.rb
class FilmsController < ApplicationController
  authorize_resource
  
  before_action :set_film, only: [:show, :edit, :update, :destroy, :review, :active, :rempicture]

  # GET /films
  # GET /films.json
  def index
    @index = true
    if params[:tag]
      @active_films = Film.where(active: true).tagged_with(params[:tag]).page params[:page]
    else
      @active_films = Film.where(active: true).page params[:page]
   end
 end

  # GET /films/suggested
  def suggested
    @films = Film.where(active: false).page params[:page]
  end

  # GET /films/1
  # GET /films/1.json
  #http://stackoverflow.com/questions/10351730/embed-youtube-video-into-rails-app
  def show
    @comment = Comment.new
    @comments = Comment.where(film: @film).order(created_at: :desc).page params[:page]
    if @film.link?
      if @film.link.include? "youtube.com"
        @video = @film.link.split('=').last
      end
    end
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Der Film wurde erfolgreich erstellt.' }
        format.json { render action: 'show', status: :created, location: @film }
      else
        format.html { render action: 'new' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Der Film wurde erfolgreich aktualisiert.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url }
      format.json { head :no_content }
    end
  end

  def review
    if @film.review params[:rid], current_user
      update_average @film
      redirect_to film_url(@film), notice: "Die Bewertung wurde gespeichert!"
    else
      redirect_to film_url(@film),
      notice: "Die Bewertung konnte nicht gespeichert werden!"
    end
  end

  def top
    @index = false
    @active_films = Film.where(active: true).order('average DESC').page params[:page]
  end

  def active
    @film.set_active
    redirect_to suggested_films_url
  end

  def rempicture
    @film.remove_picture!
    @film.picture = nil
    @film.save
    redirect_to edit_film_path(@film)
  end

  def tagsearch
    @films = Film.findbytags params[:tag_names]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:title, :tag_list, :picture, :description, :link, :active, :producer, :actor, :director, :year)
    end

    #Berechnung der Durchschnittsbewertung für einen Film.
    def update_average film
      count = film.reviews.size
      summe = 0.0
      film.reviews.each do |r|
        summe = summe + r.note
      end
      film.average = (summe  / count).round(2)
      film.save
    end

    def comment_params
      params.require(:comment).permit(:text)
    end
  end

RubyMovies/app/helpers/films_helper.rb
module FilmsHelper
	def getyear film
		unless film.year.nil?
			"(#{film.year})"
		else
			""
		end
	end
end

RubyMovies/app/views/films/_comment.html.erb
<%= form_for([@film, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RubyMovies/app/views/films/_form.html.erb
<%= form_for(@film, :html => {:multipart => true}) do |f| %>
  <% if @film.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>

      <ul>
      <% @film.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Titel" %><br>
    <%= f.text_field :title %>
  </div>
    <div class="field">
    <%= f.label :tag_list, "Tags (mit Komma trennen)" %><br>
    <%= f.text_field :tag_list %>
  </div>
    <div class="field">
    <%= f.label :actor, "Schauspieler" %><br>
    <%= f.text_field :actor %>
  </div>
    <div class="field">
    <%= f.label :producer, "Produzent" %><br>
    <%= f.text_field :producer %>
  </div>
    <div class="field">
    <%= f.label :director, "Regisseur" %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :year, "Erscheinungsjahr" %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :description, "Beschreibung" %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :link, "Link" %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <label>Bild</label>
    <br />
    <%= image_tag(@film.picture_url, height:'110', width:'95') if @film.picture? %>
    <br/>
    Neues Bild:
    <br />
    <%= f.file_field :picture %>
  </div>
  <% unless params[:id].nil? %>
    <div class="field">
      <% if @film.picture? %>
        <%= link_to "Bild löschen", rempicture_film_path(@film), method: :delete %>
      <% end %>
    </div>
  <% end %>
  
  <% if moderator_signed_in? || admin_signed_in? %>
    <div class="field">
      <%= f.label :active %>
      <%= f.check_box :active %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RubyMovies/app/views/films/_rev.html.erb
<% i = 0 %>
<% 5.times do %>
	<% i += 1 %>
    <%= link_to i, film_review_path(@film, i), method: :post %>
<% end %>

RubyMovies/app/views/films/_review.html.erb
<strong>Durchschnittsbewertung:</strong>
<%  if film.average.nil?
        d = "Keine Bewertung"
    else
    	d = film.average 
    end %>
<%= d %>

RubyMovies/app/views/films/_tags.html.erb
<!-- http://railscasts.com/episodes/382-tagging -->
<strong>Tags:</strong> 
<% if film.tag_list.empty? %>
	Keine Tags vorhanden
<% else %>
	<%= raw film.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
<% end %>

RubyMovies/app/views/films/_video.html.erb
<iframe width="560" height="349" src="<%= "http://www.youtube.com/embed/"+@video %>"></iframe>

RubyMovies/app/views/films/edit.html.erb
<h1>Film bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @film %> |
<%= back %>

RubyMovies/app/views/films/index.html.erb
<div id="cloud">
    <h2>Filme nach Kategorien</h2>
	<%= render 'cloud' %>
</div>

<% if params[:tag] %>
	<h2>Alle Filme mit Tag: <%= params[:tag] %></h2>
<% else %>
	<h2>Alle Filme</h2>
<% end %>

<%= render 'index' %>

<%= paginate @active_films %>

RubyMovies/app/views/films/new.html.erb
<% if admin_signed_in? || moderator_signed_in? %>
	<h1>Film hinzufügen</h1>
<% else %>
	<h1>Film vorschlagen</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Zurück', films_path %>

RubyMovies/app/views/films/searchresult.html.erb
<%= render :partial => "filmtable", :locals => { :films => @films, :activefilms => true} %>

RubyMovies/app/views/films/show.html.erb
<%= render 'manage' %>  
<%= link_to 'Zurück', films_path %>

<p>
  <strong>Title:</strong>
  <%= @film.title %>
</p>

<p>
  <strong>Bild:</strong>
  <br />
  <%= image_tag(@film.picture) %>
</p>

<p>
  <strong>Schauspieler:</strong>
  <%= @film.actor %>
</p>
<p>
  <strong>Produzent:</strong>
  <%= @film.producer %>
</p>
<p>
  <strong>Regisseur:</strong>
  <%= @film.director %>
</p>
<p>
  <strong>Erscheinungsjahr:</strong>
  <%= @film.year %>
</p>
<p>
  <strong>Beschreibung:</strong>
  <%= @film.description %>
</p>

<p>
  <strong>Link:</strong>
  <% unless @video.nil? %>
    <br />
    <%= render 'video' %>
  <% else %>
    <%= link_to "Link", @film.link %>
  <% end %>
</p>

<p><%= render :partial => "tags", :locals => { :film => @film} %></p>

<p><%= render :partial => "review", :locals => { :film => @film} %></p>

<% if user_signed_in? %>
  <p>
    <strong>Ihre Bewertung:</strong>
    <% if user_has_already_reviewed? @film %>
      <%= user_review(@film) %>
    <% else %>
      <%= render 'rev' %>
    <% end %>
  </p>
<% end %>

<%= render 'comment' if user_signed_in? %>

<h3>Kommentare:</h3>
<% if @comments.empty? %>
	<p>Keine Kommentare vorhanden!</p>
<% end %>

<% @comments.each do |comment| %>
  <p>
    <strong>Von: </strong><%= comment.user.name %>
    <br />
    <strong>Datum: </strong><%= comment.created_at.to_formatted_s(:db) %>
    <p><%= comment.text %></p>
    <% if admin_signed_in? || moderator_signed_in? %>
      <%= link_to 'Kommentar löschen', comments_destroy_path(comment), method: :delete %>
      <br />
    <% end %>
  </p>
<% end %>

<%= paginate @comments %>

RubyMovies/app/views/films/suggested.html.erb
<h2>Vorgeschlagene Filme</h2>

<% if @films.empty? %>
  <p>Zur Zeit keine vorgeschlagenen Filme vorhanden.</p>
<% else %>
  <%= render :partial => "filmtable", :locals => { :films => @films, :activefilms => false} %>
  <%= paginate @films %>
<% end %>

RubyMovies/app/views/films/tagsearch.html.erb
<%= form_tag('search', method: :get) do %>
	<% Film.where(active: true).tag_counts.each do |tag| %>
		<%= tag.name %>: 
		<!-- http://apidock.com/rails/ActionView/Helpers/FormTagHelper/check_box_tag -->
		<% unless params[:tag_names].nil? %>
			<% if params[:tag_names].include? tag.name %>
				<%= check_box_tag 'tag_names[]', tag.name, true %>
			<% else %>
				<%= check_box_tag 'tag_names[]', tag.name %>
			<% end %>
		<% else %>
				<%= check_box_tag 'tag_names[]', tag.name %>
		<% end %>
	<% end %>
	<%= submit_tag "Suche" %>
<% end %>
<% unless @films.nil? %>
	<%= render :partial => "filmtable", :locals => { :films => @films, :activefilms => true} %>
<% end %>	

RubyMovies/app/views/films/top.html.erb
<h2>Top-Filme</h2>

<%= render 'index' %>

<%= paginate @active_films %>