RubyMovies/config/routes.rb
RubyMovies::Application.routes.draw do

  get "/blocklists", to: "blocklists#index", as: "blocklist"
  delete "/blocklists/:blocked_user", to: "blocklists#destroy", as: "delete_blocklist"
  
  get "quizzes/new"
  get "quizzes/create"
  get "/questions/solve", to: "questions#solve"
  get "questions/quiz", to: "questions#quiz", as: "quiz_start"
  get "questions/quiz/new", to: "questions#new_quiz", as: "quiz_new"
  resources :questions do
    member do 
      post "active"
    end
  end

  get "messages/new/:mid", to: "messages#new", as: "message_respond"
  get "messages/outbox", to: "messages#outbox", as: "outbox_messages"
  get "messages/inbox", to: "messages#index", as: "inbox_messages"
  put "messages/block/:user", to: "messages#block", as: "block_user"
  delete "messages/:id", to: "messages#delete", as: "delete_message"
  resources :messages
  
  get 'search', to: 'films#tagsearch', as: "tag_search"
  get 'searchresult', to: 'films#searchresult', as: "search_result_films"
  get 'tags/:tag', to: 'films#index', as: :tag
  
  delete "comments/destroy/:id", to: "comments#destroy", as: "comments_destroy"

  get "films/top", to: "films#top", as: "films_top"
  post "films/:id/review/:rid", to: "films#review", as: "film_review"
  get "/films/suggested", to: "films#suggested", as: "suggested_films"
  resources :films do
    member do
      post "active"
      delete "rempicture"
    end
  end
  resources :films
  get "users/list", as: "manage_users"
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users do 
    member do
      get "promote"
      post "promote"
    end
  end

  resources :films do
    resources :comments
  end

  root to: "films#index"

  

end

RubyMovies/app/models/question.rb
class Question < ActiveRecord::Base

	has_many :quiz, :class_name => 'Quiz', :foreign_key => 'q1_id'

	#http://edgeguides.rubyonrails.org/active_record_validations.html
	validates :solution, :numericality => {only_integer: true, less_than: 5, greater_than: 0}, :allow_blank => false
	validates :title, :presence => true
	validates :answer1, :presence => true
	validates :answer2, :presence => true
	validates :answer3, :presence => true
	validates :answer4, :presence => true

	paginates_per 1

	#http://stackoverflow.com/questions/5342270/rails-3-get-random-record
	def self.get_n_questions n 
		Question.where(active: true).order("RANDOM()").limit(n)
	end

	def correct solution
		unless solution.nil?
			if solution == self.solution.to_s
				"Die Antwort ist richtig"
			else
				if solution == "0"
					""
				else
					"Die Antwort ist falsch"
				end
			end
		end
	end

	def set_active
		self.active = true
		self.save
	end
end

RubyMovies/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  authorize_resource

  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  def active
    q = Question.find(params[:id]).set_active
    redirect_to questions_url
  end

  def quiz
    quiz = Quiz.get_quiz current_user
    @quiz = Kaminari.paginate_array(quiz.to_a).page(params[:page]).per(1)
  end

  def solve
    quiz = Quiz.where(user: current_user).take
    @quiz = Kaminari.paginate_array(quiz.to_a).page(params[:page]).per(1)
    @solution = Question.find(params[:id]).correct params[:answer]
    render action: "quiz"
  end

  def new_quiz
    Quiz.new_quiz current_user
    redirect_to quiz_start_path, notice: "Neues Quiz erstellt."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :answer1, :answer2, :answer3, :answer4, :solution, :active)
    end
  end

RubyMovies/app/helpers/questions_helper.rb
module QuestionsHelper
	def checked? id
		if params[:answer] == id
			true
		else
			false
		end
	end

	def active question
		if question.active
			"Ja"
		else
			"Nein"
		end
	end
end

RubyMovies/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Frage" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :answer1, "1. Antwortmöglichkeit" %><br>
    <%= f.text_field :answer1 %>
  </div>
  <div class="field">
    <%= f.label :answer2, "2. Antwortmöglichkeit" %><br>
    <%= f.text_field :answer2 %>
  </div>
  <div class="field">
    <%= f.label :answer3, "3. Antwortmöglichkeit" %><br>
    <%= f.text_field :answer3 %>
  </div>
  <div class="field">
    <%= f.label :answer4, "4. Antwortmöglichkeit" %><br>
    <%= f.text_field :answer4 %>
  </div>
  <div class="field">
    <%= f.label :solution, "Korrekte Antwortmöglichkeit (1-4)" %><br>
    <%= f.number_field :solution %>
  </div>
  <% if admin_moderator_signed_in? %>
    <div class="field">
      <%= f.label :active %><br>
      <%= f.check_box :active %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RubyMovies/app/views/questions/_quizform.html.erb
<%= form_tag({controller: "questions", action: "solve"}, {method: :get}) do %>
	<% @quiz.each do |question| %>
		<% next if question.nil? %>
		<p><%= @solution %></p>
		<p>
			<%= question.title %>
			<br />
			<p>
				<%= radio_button_tag("answer", "1", checked?("1")) %>
				<%= label_tag(:answer_answer1, question.answer1) %>
			</p>
			<p>
				<%= radio_button_tag("answer", "2", checked?("2")) %>
				<%= label_tag(:answer_answer2, question.answer2) %>
			</p>
			<p>
				<%= radio_button_tag("answer", "3", checked?("3")) %>
				<%= label_tag(:answer_answer3, question.answer3) %>
			</p>
			<p>
				<%= radio_button_tag("answer", "4", checked?("4")) %>
				<%= label_tag(:answer_answer4, question.answer4) %>
			</p>
			<br />
			<%= submit_tag "Antworten" %>
		</p>
		<%= hidden_field_tag 'id', question.id %>
		<%= hidden_field_tag 'page', params[:page] %>

	<% end %>
	<%= paginate @quiz, :params => {:answer => "0"} %>

<% end %>

RubyMovies/app/views/questions/edit.html.erb
<h1>Frage bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @question %> |
<%= link_to 'Zurück', questions_path %>

RubyMovies/app/views/questions/index.html.erb
<h2>Alle Fragen</h2>

<table>
  <thead>
    <tr>
      <th>Frage</th>
      <th>Aktiv</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td width="200px"><%= question.title %></td>
        <td><%= active question %></td>
        <td><%= link_to 'Anzeigen', question_path(question) %></td>
        <td><%= link_to 'Bearbeiten', edit_question_path(question) %></td>
        <td><%= link_to 'Löschen', question, method: :delete, data: { confirm: 'Sind Sie sicher?' } %></td>
        <td><%= link_to 'Freischalten', active_question_path(question.id), method: :post unless question.active %></td>
      </tr>
    <% end %>
  </tbody>
</table>

RubyMovies/app/views/questions/new.html.erb
<h1>Frage einreichen</h1>

<%= render 'form' %>

<%= link_to 'Zurück', root_path %>

RubyMovies/app/views/questions/quiz.html.erb
<h2>Filmquiz</h2>
<%= link_to "Neues Quiz erstellen", quiz_new_path %>
<%= render "quizform" %>

RubyMovies/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frage:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Antwort 1:</strong>
  <%= @question.answer1 %>
</p>

<p>
  <strong>Antwort 2:</strong>
  <%= @question.answer2 %>
</p>

<p>
  <strong>Antwort 3:</strong>
  <%= @question.answer3 %>
</p>

<p>
  <strong>Antwort 4:</strong>
  <%= @question.answer4 %>
</p>

<p>
  <strong>Lösung:</strong>
  <%= @question.solution %>
</p>

<p>
  <strong>Freigeschaltet:</strong>
  <%= active @question %>
</p>

<%= link_to 'Bearbeiten', edit_question_path(@question) %> |
<%= link_to 'Zurück', questions_path %>